=== AgriculturalModelExchangeInitiative/Crop2ML/ModelUnit.dtd
<!--
FILE : ModelUnit.dtd

CREATED : 2018

LAST MODIFIED : 2020

AUTHOR : Agricultural Models Exchange Initiative

DESCRIPTION : This document contains a DTD corresponding to the syntax rules
  defined in the Crop2ML model unit's Specification for Crop2ML 1.1. This
  specification is available at
    https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd

COPYRIGHT : (2018).
-->

<!ELEMENT ModelUnit (Description,Inputs?,Outputs?,Initialization?,Function*, Algorithm+,Parametersets,Testsets)>
<!ATTLIST ModelUnit
  name CDATA #REQUIRED
  modelid CDATA #REQUIRED
  timestep CDATA #IMPLIED
  version CDATA #REQUIRED>

<!ELEMENT Description (Title,Authors,Institution,URI?,Reference?,ExtendedDescription, ShortDescription?)>
<!ATTLIST Description>

<!ELEMENT Inputs (Input)+>
<!ATTLIST Inputs>

<!ELEMENT Outputs (Output*)>
<!ATTLIST Outputs>

<!ELEMENT Algorithm (#PCDATA)>
<!ATTLIST Algorithm
  language CDATA #REQUIRED
  platform CDATA #IMPLIED
  filename CDATA #IMPLIED
  function CDATA #IMPLIED>

<!ELEMENT Parametersets (Parameterset*)>
<!ATTLIST Parametersets>

<!ELEMENT Testsets (Testset*)>
<!ATTLIST Testsets>

<!ELEMENT Function (#PCDATA)>
<!ATTLIST Function
	name CDATA #REQUIRED
	language CDATA #REQUIRED
	filename CDATA #IMPLIED
	type (internal|external) #REQUIRED
	description CDATA #IMPLIED>

<!ELEMENT Initialization (#PCDATA)>
<!ATTLIST Initialization
	name CDATA #REQUIRED
	language CDATA #REQUIRED
	filename CDATA #IMPLIED>	

<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title>

<!ELEMENT Authors (#PCDATA)>
<!ATTLIST Authors>

<!ELEMENT Institution (#PCDATA)>
<!ATTLIST Institution>

<!ELEMENT URI (#PCDATA)>
<!ATTLIST URI>

<!ELEMENT Reference (#PCDATA)>
<!ATTLIST Reference>

<!ELEMENT ExtendedDescription (#PCDATA)>
<!ATTLIST ExtendedDescription>

<!ELEMENT ShortDescription (#PCDATA)>
<!ATTLIST ShortDescription>

<!ELEMENT Input EMPTY>
<!ATTLIST Input
  name NMTOKEN #REQUIRED
  datatype (CHAR|STRING|INT|DOUBLE|BOOLEAN|DATE|CHARARRAY|STRINGARRAY|INTARRAY|DOUBLEARRAY|BOOLEANARRAY|DATEARRAY|CHARLIST|STRINGLIST|INTLIST|DOUBLELIST|BOOLEANLIST|DATELIST) #REQUIRED 
  description CDATA #REQUIRED
  default CDATA #IMPLIED
  len CDATA #IMPLIED
  max CDATA #IMPLIED
  min CDATA #IMPLIED
  inputtype (variable|parameter) #REQUIRED
  parametercategory (constant|species|genotypic|soil|private) #IMPLIED
  variablecategory (state|rate|auxiliary|exogenous) #IMPLIED
  unit CDATA #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Output EMPTY>
<!ATTLIST Output
  name NMTOKEN #REQUIRED
  datatype (CHAR|STRING|INT|DOUBLE|BOOLEAN|DATE|CHARARRAY|STRINGARRAY|INTARRAY|DOUBLEARRAY|BOOLEANARRAY|DATEARRAY|CHARLIST|STRINGLIST|INTLIST|DOUBLELIST|BOOLEANLIST|DATELIST) #REQUIRED 
  description CDATA #REQUIRED
  len CDATA #IMPLIED
  max CDATA #IMPLIED
  min CDATA #IMPLIED
  variablecategory (state|rate|auxiliary|exogenous) #IMPLIED
  unit CDATA #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Parameterset (Param*)>
<!ATTLIST Parameterset
  description CDATA #REQUIRED
  name NMTOKEN #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Testset (Test*)>
<!ATTLIST Testset
  description CDATA #REQUIRED
  name CDATA #REQUIRED
  parameterset NMTOKEN #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Test (InputValue*, OutputValue+)>
<!ATTLIST Test
  description CDATA #IMPLIED
  name CDATA #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Param (#PCDATA) >
<!ATTLIST Param name CDATA #REQUIRED >

<!ELEMENT InputValue (#PCDATA) >
<!ATTLIST InputValue name CDATA #REQUIRED >

<!ELEMENT OutputValue (#PCDATA) >
<!ATTLIST OutputValue name CDATA #REQUIRED >
<!ATTLIST OutputValue description CDATA #IMPLIED >
<!ATTLIST OutputValue precision CDATA #IMPLIED >

=== AgriculturalModelExchangeInitiative/Crop2ML/old_example/BioMA/Photoperiod.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="Photoperiod" timestep="1" name="Example" version="001">
	<Description>
		<Title>Photoperiod</Title>
		<Authors>various</Authors>
		<Institution>JRC - CREA</Institution>
		<URI></URI>
		<ExtendedDescription>Photoperiod effect on development - Stockle, C.O., Donatelli, M., Nelson, R., 2003. CropSyst, a cropping systems simulation model. European Journal of Agronomy, 18, 289-307</ExtendedDescription>
	</Description>
	<Inputs>
		<Input name="PhotoInhibition" datatype="DOUBLE" inputtype="parameter" parametercategory="constant" min="1" max="24" default="14" unit="hour" description="Daylenght to inhibit flowering" />
		<Input name="PhotoInsensitivity" datatype="DOUBLE" inputtype="parameter" parametercategory="constant" min="1" max="24" default="6" unit="hour" description="Daylenght for insensitivity of photoperiod" />		
		<Input name="DayLenght" datatype="DOUBLE" inputtype="variable" min="0" max="24" default="12" unit="hour" description="Day lenght"/>		
	</Inputs>
	<Outputs>
		<Output name="PhotoPeriodFactor" datatype="DOUBLE" min="0" max="1"  unit="unitless" description="Photoperiod factor"/>
	</Outputs>
	<Algorithm language="C#" platform="bioma">
		<![CDATA[ 
				double Dl = Daylenght;                
                double DlIns = PhotoInsensitivity;
                double DlInb = PhotoInhibition;
                double PhotoPeriodFactor;

                PhotoPeriodFactor = (DlInb - Dl) / (DlInb - DlIns);
                if (DlIns > DlInb)
                {
                    PhotoPeriodFactor = (Dl - DlInb) / (DlIns - DlInb);
                }
                if (PhotoPeriodFactor < 0)
                {
                    PhotoPeriodFactor = 0;
                }
                if (PhotoPeriodFactor > 1)
                {
                    PhotoPeriodFactor = 1;
                }                
		]]>
	</Algorithm>
	<Parametersets>
		<Parameterset name="default" description="default values">
			<Param name="PhotoInhibition">14</Param>
			<Param name="PhotoInsensitivity">6</Param>			
		</Parameterset>		
	</Parametersets>
	<Testsets>
		<Testset name="check 1" parameterset="default" description="some test values">
			<Test name="check 1 1">
				<InputValue name="DayLenght">16</InputValue>				
				<OutputValue name="PhotoPeriodFactor">0</OutputValue>				
			</Test>
			<Test name="check 1 2">
				<InputValue name="DayLenght">12</InputValue>				
				<OutputValue name="PhotoPeriodFactor">0.25</OutputValue>		
			</Test>			
		</Testset>		
	</Testsets>
</ModelUnit>

=== AgriculturalModelExchangeInitiative/Crop2ML/old_example/BioMA/GrowingDegreeDaysTemperature.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="GrowingDegreeDaysTemperature" timestep="1" name="Example" version="001">
	<Description>
		<Title>GrowingDegreeDaysTemperature</Title>
		<Authors>various</Authors>
		<Institution>JRC - CREA</Institution>
		<URI></URI>
		<ExtendedDescription>Growing degree days based on temperature - Confalonieri, R., Gusberti, D., Acutis, M., 2006. Comparison of WOFOST, CropSyst and WARM for simulating rice growth (Japonica type – short cycle varieties). Italian Journal of Agrometeorology, 3, 7-16</ExtendedDescription>
	</Description>
	<Inputs>
		<Input name="BaseTemperatureDevelopment" datatype="DOUBLE" inputtype="parameter" parametercategory="constant" min="-10" max="40" default="10" unit="°C" description="Base temperature for development" />
		<Input name="CutoffTemperatureDevelopment" datatype="DOUBLE" inputtype="parameter" parametercategory="constant" min="10" max="50" default="40" unit="°C" description="Cutoff temperature for development" />		
		<Input name="AirTemperatureAverage" datatype="DOUBLE" inputtype="variable" min="-30" max="55" default="25" unit="°C" description="Daily average air temperature"/>		
		<Input name="GrowingDegreeDaysTemperature" datatype="DOUBLE" inputtype="variable" min="0" max="8000" default="100" unit="°C" description="Potential growing degree days calculated on temperature"/>		
	</Inputs>
	<Outputs>
		<Output name="GrowingDegreeDaysTemperature" datatype="DOUBLE" min="0" max="8000"  unit="°C" description="Potential growing degree days calculated on temperature"/>
		<Output name="GrowingDegreeDaysTemperatureRate" datatype="DOUBLE" min="0" max="50"  unit="°C" description="Potential daily rate of growing degree days accumulation based on temperature"/>		
	</Outputs>
	<Algorithm language="C#">
		<![CDATA[ 
				double Tavg = AirTemperatureAverage;

                if (Tavg <= BaseTemperatureDevelopment)
                {
                    GrowingDegreeDaysTemperatureRate = 0;
                }
                else if (Tavg >= CutoffTemperatureDevelopment)
                {
                    GrowingDegreeDaysTemperatureRate = CutoffTemperatureDevelopment - BaseTemperatureDevelopment;
                }
                else
                {
                    GrowingDegreeDaysTemperatureRate = Tavg - BaseTemperatureDevelopment;
                }
				GrowingDegreeDaysTemperature = GrowingDegreeDaysTemperature + GrowingDegreeDaysTemperatureRate;
		]]>
	</Algorithm>
	<Parametersets>
		<Parameterset name="default" description="default values">
			<Param name="BaseTemperatureDevelopment">10</Param>
			<Param name="CutoffTemperatureDevelopment">40</Param>			
		</Parameterset>		
	</Parametersets>
	<Testsets>
		<Testset name="check 1" parameterset="default" description="some test values">
			<Test name="check 1 1">
				<InputValue name="AirTemperatureAverage">16</InputValue>
				<InputValue name="GrowingDegreeDaysTemperature">5</InputValue>
				<OutputValue name="GrowingDegreeDaysTemperature">11</OutputValue>
				<OutputValue name="GrowingDegreeDaysTemperatureRate">6</OutputValue>
			</Test>
			<Test name="check 1 2">
				<InputValue name="AirTemperatureAverage">46</InputValue>
				<InputValue name="GrowingDegreeDaysTemperature">5</InputValue>
				<OutputValue name="GrowingDegreeDaysTemperature">35</OutputValue>
				<OutputValue name="GrowingDegreeDaysTemperatureRate">30</OutputValue>
			</Test>
			<Test name="check 1 3">
				<InputValue name="AirTemperatureAverage">-1</InputValue>
				<InputValue name="GrowingDegreeDaysTemperature">5</InputValue>
				<OutputValue name="GrowingDegreeDaysTemperature">5</OutputValue>
				<OutputValue name="GrowingDegreeDaysTemperatureRate">0</OutputValue>
			</Test>
		</Testset>		
	</Testsets>
</ModelUnit>

=== AgriculturalModelExchangeInitiative/Crop2ML/example/usecase/DayLength.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC "-//SIMPLACE/DTD SOL 1.0//EN" "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/xml_representation/master/ModelUnit.dtd">
<ModelUnit modelid="1" timestep="1" name ="DayLength" version="1.0">
	<Description>
		<Title>STMPsimCalculator</Title>
		<Authors>Andreas Enders</Authors>
		<Institution>Crop Science Group Bonn</Institution>
		<URI>http://www.simplace.net/doc/simplace_modules/class_net.simplace.sim.components.soil.temperature.STMPsimCalculator.html</URI>
		<Abstract>Calculates the DayLength.</Abstract>
	</Description>
	<Inputs>
		<Input name="pDaylength" datatype="floatARRAY" inputtype="parameter" parametercategory="constant" min="0" max="1441" default="0" unit="d" description="" />
		<Input name="cLatitude"  description="Latitude of the simulated location" datatype="float" inputtype="parameter" parametercategory="constant" min="0" max="90" default="60" unit="" />
		<Input name="iDayOfYear" description="Day Of Year" datatype="float" inputtype="Variable" parametercategory="constant" min="" max="" default="100" unit="" />

	</Inputs>
	<Outputs>
		<Output name="DayLength" datatype="INT"   min="0" max="1441"  unit="" description="Day Length in minutes"/>
	</Outputs>
	<Algorithm language="Pyhton_ext" platform="OPENALEA"><![CDATA[
	
		dayLengthArray = np.arange(370)
		
		for i in range(0,370):
		{
			TIME = i
			SINLAT = float(np.sin(np.pi * cLatitude/ 180))
			COSLAT = float(np.cos(np.pi * cLatitude / 180))

			SINDCM = float(np.sin(np.pi * 23.45 / 180))

			SINDEC = (-SINDCM * np.cos(2 * np.pi * (TIME + 10) / 365))
			COSDEC = float( np.sqrt(1 - SINDEC * SINDEC))

			A = float(SINLAT * SINDEC)
			B = float(COSLAT * COSDEC)

			arg = float(A / B)
			if (arg > 1): arg = 1
			if (arg < -1): arg = -1
			tDayLength = float(12 * (1 + (2 / np.pi) * np.arcsin(arg)))

			dayLengthArray[i] = int(round(tDayLength * 60))
		}

		pDaylength=dayLengthArray
		DayLength = pDaylength[iDayOfYear]
	
		]]>
	</Algorithm>
	<Parametersets>
		<Parameterset name="first" description="some values for cold weather">
			<Param name="cLatitude">20</Param>

		</Parameterset>
	</Parametersets>
	<Testsets>
		<Testset name="check soil temp1" parameterset="first" description="some values in there">
			<Test name="daytest">
				<InputValue name="iDayOfYear">15</InputValue>
				<OutputValue name="DayLength" precision = "2">655</OutputValue>
			</Test>
		</Testset>
	</Testsets>
</ModelUnit>

=== AgriculturalModelExchangeInitiative/Crop2ML/example/bioma/TemperatureSum.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ModelUnit PUBLIC "-//SIMPLACE/DTD SOL 1.0//EN" "ModelUnit.dtd">
<ModelUnit uniqueid="TemperatureSum" timestep="1" name="Example">
	<Description>
		<Title>TemperatureSum</Title>
		<Authors>various</Authors>
		<Institution>JRC - CREA</Institution>
		<URI></URI>
		<Abstract>Temperature sum based on the calculation of development rate - Van Keulen, H., Wolf, J., 1986. Modelling of agricultural production: weather soils and crops. Simulation Monographs. Pudoc, Wageningen, The Netherlands, pp. 479</Abstract>
	</Description>
	<Inputs>
		<Input name="DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_X1" datatype="DOUBLE" inputtype="parameter" parametertype="constant" min="-10" max="50" default="4" unit="°C" description="Daily increase of temperature sum function on average temperature - temperature1" />
		<Input name="DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_X2" datatype="DOUBLE" inputtype="parameter" parametertype="constant" min="-10" max="50" default="35" unit="°C" description="Daily increase of temperature sum function on average temperature - temperature2" />
		<Input name="DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_Y1" datatype="DOUBLE" inputtype="parameter" parametertype="constant" min="-10" max="50" default="0" unit="unitless" description="Daily increase of temperature sum function on average temperature - increase1" />
		<Input name="DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_Y2" datatype="DOUBLE" inputtype="parameter" parametertype="constant" min="-10" max="50" default="31" unit="unitless" description="Daily increase of temperature sum function on average temperature - increase2" />
		<Input name="AirTemperatureAverage" datatype="DOUBLE" inputtype="variable"  min="-25" max="50" default="10" unit="°C" description="Daily average of air temperature"/>		
		<Input name="GrowingDegreeDaysTemperature" datatype="DOUBLE" inputtype="variable" min="0" max="8000" default="100" unit="°C-day" description="Potential growing degree days calculated on temperature, of previous day"/>		
	</Inputs>
	<Outputs>
		<Output name="GrowingDegreeDaysTemperature" datatype="DOUBLE"  min="0" max="8000"  unit="°C-day" description="Potential growing degree days calculated on temperature, of current day"/>		
		<Output name="GrowingDegreeDaysTemperatureRate" datatype="DOUBLE" min="0" max="50"  unit="°C-day" description="Potential daily rate of growing degree days accumulation based on temperature"/>
		
	</Outputs>
	<Algorithm language="C#">
		<![CDATA[ 
				Tavg = AirTemperatureAverage;
				if(Tavg<=DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_X1) GrowingDegreeDaysTemperatureRate=DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_Y1
				if(Tavg>DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_X1 && Tavg<DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_X2){
					double b = (DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_Y2 - DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_Y1) / (DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_X2 - DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_X1);					
					GrowingDegreeDaysTemperatureRate=Tavg * b + DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_Y1;
					}
                if(Tavg>=DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_X2) GrowingDegreeDaysTemperatureRate=DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_Y2
				GrowingDegreeDaysTemperature = GrowingDegreeDaysTemperature + GrowingDegreeDaysTemperatureRate;
		]]>
	</Algorithm>
	<Parametersets>
		<Parameterset name="default" description="default values">
			<Param name="DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_X1">4</Param>
			<Param name="DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_X2">35</Param>	
			<Param name="DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_Y1">0</Param>
			<Param name="DailyIncreaseTempSumFunctionOfAverageT_DTSMTB_Y2">31</Param>	
			
		</Parameterset>		
	</Parametersets>
	<Testsets>
		<Testset name="check 1" parameterset="default" description="some test values">
			<Test name="check 1 1">
				<InputValue name="AirTemperatureAverage">16</InputValue>				
				<InputValue name="GrowingDegreeDaysTemperature">1</InputValue>				
				<OutputValue name="GrowingDegreeDaysTemperature">13</OutputValue>				
				<OutputValue name="GrowingDegreeDaysTemperatureRate">12</OutputValue>				
			</Test>
			<Test name="check 1 2">
				<InputValue name="AirTemperatureAverage">3</InputValue>				
				<InputValue name="GrowingDegreeDaysTemperature">1</InputValue>				
				<OutputValue name="GrowingDegreeDaysTemperature">1</OutputValue>				
				<OutputValue name="GrowingDegreeDaysTemperatureRate">0</OutputValue>					
			</Test>			
			<Test name="check 1 2">
				<InputValue name="AirTemperatureAverage">50</InputValue>				
				<InputValue name="GrowingDegreeDaysTemperature">1</InputValue>				
				<OutputValue name="GrowingDegreeDaysTemperature">32</OutputValue>				
				<OutputValue name="GrowingDegreeDaysTemperatureRate">31</OutputValue>					
			</Test>			
		</Testset>		
	</Testsets>
</ModelUnit>
